# Generated by Django 6.1.1 on 2026-10-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='Anónimo', max_length=100),
            preserve_default=False,
        ),
    ]
